version: '3'

services:
  wordpress1:
    image: wordpress
    restart: on-failure
    ports:
      - "8081:80"
    volumes:
      - /var/www/html/wp-content/:/var/www/html/wp-content/uploads
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 10s
      retries: 3


  wordpress2:
    image: wordpress
    restart: on-failure
    ports:
      - "8082:80"
    volumes:
      - /var/www/html/wp-content/:/var/www/html/wp-content/uploads
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 10s
      retries: 3

  nginx:
    build:
      context: .
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
